### ISSUE TITLE
通用 dao 可以和列名一起生成吗，感觉使用起来比直接写 gplus 更方便

### ISSUE THREAD

**Issue by zundaren** [acmestack/gorm-plus#13]

**Comment by zouchangfu** [comment]
可以的，我重构了代码，等会儿我发个新版本，新版本不需要生成代码了

**Comment by zundaren** [comment]
> 可以的，我重构了代码，等会儿我发个新版本，新版本不需要生成代码了

还有个问题要，使用 dao 以后返回的是个指针，如果查不到数据按理说指针应该是个 nil, 如果是值类型那应该是有默认值

**Comment by zouchangfu** [comment]
现在统一返回的都是指针类型，没有默认值

**Comment by zundaren** [comment]
那大佬可以加个 withcontext吗，用来日志打印上下文的信息

**Comment by zouchangfu** [comment]
可以呀

**Comment by zundaren** [comment]
感谢大佬，强啊
