### ISSUE TITLE
dao现在还不能设置 context,要如何安全的操作

### ISSUE THREAD

**Issue by zundaren** [acmestack/gorm-plus#18]
如果获取 db设置 context再次设置到 dao，这会有问题
gplus.Init(dao.Db().WithContext(ctx))

接口操作
第一次不设置context save操作
第二次设置 context get操作

再次调用接口结果context canceled

**Comment by zouchangfu** [comment]
具体可以看看gorm的文档，应该不是gorm-plus的问题

**Comment by zundaren** [comment]
> 具体可以看看gorm的文档，应该不是gorm-plus的问题

应该是 db clone的问题，你的dao操作都是同一个db，如果修改了 db 其他的操作会有影响

**Comment by zouchangfu** [comment]
> > 具体可以看看gorm的文档，应该不是gorm-plus的问题
> 
> 应该是 db clone的问题，你的dao操作都是同一个db，如果修改了 db 其他的操作会有影响

哦哦，我理解你的意思了，我找个时间改一下，或者你有时间的话，也可以研究一下怎么改比较好，提个pr上来

**Comment by zundaren** [comment]
> > > 具体可以看看gorm的文档，应该不是gorm-plus的问题
> > 
> > 
> > 应该是 db clone的问题，你的dao操作都是同一个db，如果修改了 db 其他的操作会有影响
> 
> 哦哦，我理解你的意思了，我找个时间改一下，或者你有时间的话，也可以研究一下怎么改比较好，提个pr上来

<img width="933" alt="image" src="https://user-images.githubusercontent.com/44863479/218019443-415fb0e3-65ca-4dcd-8b3b-d00a279e304e.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/44863479/218019483-4ee3cc34-767a-4311-928a-70e595573dc4.png">
大佬，我在 dao里面设置db属性，每次操作context生成新的 dao，测试了下功能都正常，context 也没错乱，就是不知道每次新生成的 dao 会不会有什么性能问题

**Comment by 0x457** [comment]
期待函数签名 增加context
