### ISSUE TITLE
updateById 操作 where 后面有两个 id 条件

### ISSUE THREAD

**Issue by zundaren** [acmestack/gorm-plus#19]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/44863479/217752981-9ba40b31-cd40-4337-81bc-1273d406f937.png"><img width="555" alt="image" src="https://user-images.githubusercontent.com/44863479/217752509-be7930a2-b6e5-4bca-b0e0-627a1fd8b93f.png"><img width="1377" alt="image" src="https://user-images.githubusercontent.com/44863479/217752662-a4fbccca-ce58-46ec-b220-577a519390a9.png">

**Comment by zouchangfu** [comment]
这个最新的版本已经改好了，你试试最新的版本

**Comment by zundaren** [comment]
> 这个最新的版本已经改好了，你试试最新的版本

好的我去测试下

**Comment by zundaren** [comment]
可以了，0.0.13正常
