### ISSUE TITLE
Can you add a function that can use map to update？

### ISSUE THREAD

**Issue by lhou705** [acmestack/gorm-plus#23]
Gorm only support use map to update column to a zero(0，false，nil etc.) value. However  now gplus can't support in this version. Will you support in the future?

**Comment by zouchangfu** [comment]
> Gorm only support use map to update column to a zero(0，false，nil etc.) value. However now gplus can't support in this version. Will you support in the future?

Support set function to update zero-valued data
For example

```go
	query, model := gplus.NewQuery[Student]()
	query.Eq(&model.ID, 16).Set(&model.Age, 0).Set(&model.Name, "")
	resultDb := gplus.Update[Student](query)
	fmt.Println(resultDb.RowsAffected)
````
