### ISSUE TITLE
can cache ColumnNameMap?

### ISSUE THREAD

**Issue by erlangzhang** [acmestack/gorm-plus#24]
can ColumnNameMap cached for same Entity? Do not call  buildColumnNameMap every time.

**Comment by zouchangfu** [comment]
> can ColumnNameMap cached for same Entity? Do not call buildColumnNameMap every time.

Yes, I will write it when I have time, or you can submit pr if you are interested

**Comment by zouchangfu** [comment]
see this https://github.com/acmestack/gorm-plus/pull/27
