### ISSUE TITLE
How to handle transaction in gorm-plus?

### ISSUE THREAD

**Issue by xgxiang** [acmestack/gorm-plus#28]
**Background & X Problem**

**Proposal and Expectation**

**Solutions & Y Problems**

**Additional context**

**Comment by zouchangfu** [comment]
![image](https://user-images.githubusercontent.com/50908453/227457950-f6e038b3-2e5c-4637-a53d-b04db028638a.png)

**Comment by xgxiang** [comment]
下面这样应该也行
// 开启事务
tx := gplus.Begin()

// 使用defer，实现遇到错误时回滚
defer tx.Rollback()

// 新增，传入tx
student := Student{Name: "zhangsan", Age: 18, Email: "123@11.com", Birthday: time.Now()}
result := gplus.Insert(&student, tx)
...

// 更新，传入tx
query, model := gplus.NewQuery[Student]()
query.Eq(&model.Name, "zhangsan").Set(&model.Age, 30)
resultDb := gplus.Update[Student](query, tx)
...

// 查询，如果需要在事务中查询，则也需要传入tx
resultStudent, db := gplus.SelectById[Student](student.ID, tx)
...

// 提交事务，否则数据库数据不更改
tx.Commit()

**Comment by zouchangfu** [comment]
有兴趣的话，可以提交一下PR

**Comment by xgxiang** [comment]
![image](https://user-images.githubusercontent.com/12162501/227493110-132e1557-698b-4f70-a106-2226a24e29b0.png)
你写的这种自动事务，也得把tx传进去，才会在事务中
