### ISSUE TITLE
后续会增加类似mybatis-plus当中自定义TypeHandler的支持么？

### ISSUE THREAD

**Issue by SantaOracle** [acmestack/gorm-plus#31]
我们有一些字段，在数据插入前需要针对他们进行json序列化、加密等操作，后续是否会有相关的typeHandler进行支持呢？

**Comment by zouchangfu** [comment]
gorm本身是支持的，https://gorm.io/zh_CN/docs/hooks.html，在调用gplus方法的时候传入自定义的gormDb就可以了
