### ISSUE TITLE
新增/修改记录时，无法选择忽略的字段

### ISSUE THREAD

**Issue by SantaOracle** [acmestack/gorm-plus#32]
在model中，create_time和modify_time字段期望在新增/修改记录时，由数据库自动变更。
之前使用gorm的写法是：

```
data := &Students{
		Class: 2,
		Name:  "Mono",
		Age:   29,
}

db.Omit("create_time", "modify_time").Create(data)
```

切换到gorm-plus后，目前是这么实现的：

```
data := &Students{
		Class: 1,
		Name:  "Speci",
		Age:   12,
}

gplus.Insert[Students](data)
```

这样会报 Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'create_time' at row 1
想问下目前gorm-plus有相关的解决方案么？

**Comment by zouchangfu** [comment]
var student Student
	db := gormDb.Omit("create_time", "modify_time")
	gplus.Insert[Student](&student, db)

**Comment by zouchangfu** [comment]
所有gorm能做到的功能，基本上你传入额外的db就可以了
