### ISSUE TITLE
selectOne和selectId 的搜索时建议使用First

### ISSUE THREAD

**Issue by tiantianlikeu** [acmestack/gorm-plus#34]
selectOne和selectId 的搜索时建议使用First

源码里面使用的limit+find。使用find后，如果查不到数据，数据接收对象被实例化了一个空的对象；并且没有gorm.ErrRecordNotFound的错误了。

**Comment by zouchangfu** [comment]
是的，我之前都是通过RowsAffected==0来判断的，不过这样判断对于查询多条的情况有误判的情况

**Comment by tiantianlikeu** [comment]
<img width="785" alt="image" src="https://github.com/acmestack/gorm-plus/assets/35363659/6cf7f689-ddf8-42d9-b459-44a842c506eb">
我的错，如果使用first 或者last   时，传进来的order by 条件会发生冲突，正确的应该是使用take。
take的话，不会默认添加 id的排序
https://gorm.io/docs/query.html
