### ISSUE TITLE
please add a flag to ignore pagination total output using functions SelectPage, SelectPageModel, SelectPageMaps

### ISSUE THREAD

**Issue by cindoralla** [acmestack/gorm-plus#37]
I have a big table, and do not want to get the total using selectPage function .
Because if I want to get the total, I can use the function `SelectCount`.
So please add a flag to not output the total in the page functions, thanks.

**Comment by zouchangfu** [comment]
This suggestion is acceptable, and if you are interested, you can also submit a PR
