### ISSUE TITLE
什么时候才有根据数据库生成实体类 CRUD功能 ，还有分页功能和事务什么时候有呀 期待你的更新

### ISSUE THREAD

**Issue by XiaoFanGitHub** [acmestack/gorm-plus#42]
什么时候才有根据数据库生成实体类 CRUD功能 ，还有分页功能和事务什么时候有呀 期待你的更新，忘回复

**Comment by afumu** [comment]
CRUD功能，分页功能，事务功能本身就是支持的呀，只不过目前还没有根据数据库生成结构体的功能
事务使用：https://github.com/acmestack/gorm-plus/issues/28

**Comment by XiaoFanGitHub** [comment]
期待你的根据数据库生成结构体的功能哦。文档能更完善一点就更好了！加油，还是很厉害。功能齐全我觉得以后星星和mybatis-plus一样多

**Comment by afumu** [comment]
> 期待你的根据数据库生成结构体的功能哦。文档能更完善一点就更好了！加油，还是很厉害。功能齐全我觉得以后星星和mybatis-plus一样多

你感兴趣的话，可以提交pr哈，加入我们一起来完善它
