### ISSUE TITLE
TestSelectListQueryModel  Error

### ISSUE THREAD

**Issue by aixj1984** [acmestack/gorm-plus#55]
2023/06/19 10:40:49 D:/test/gorm-plus/gplus/dao.go:172
[0.000ms] [rows:0] SELECT * FROM `Users` ORDER BY username DESC,age ASC
--- FAIL: TestSelectListQueryModel (0.00s)
panic: interface conversion: interface {} is *tests.UserVo, not *tests.UserVo (types from different scopes) [recovered]
        panic: interface conversion: interface {} is *tests.UserVo, not *tests.UserVo (types from different scopes)

goroutine 512 [running]:
testing.tRunner.func1.2({0x4f4280, 0xc00034f8f0})
        D:/Program Files/golang/go1.20.3/src/testing/testing.go:1526 +0x24e
        D:/Program Files/golang/go1.20.3/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        D:/Program Files/golang/go1.20.3/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL    github.com/acmestack/gorm-plus/tests    8.290s
PS D:\test\gorm-plus\tests>

**Comment by afumu** [comment]
拉一下最新的代码，main分支的代码最近一直在变动

**Comment by afumu** [comment]
最近在更新新的功能，main分支的代码可能有些变动

**Comment by aixj1984** [comment]
新代码已经解决，问题单关闭了
