### ISSUE TITLE
为什么自动给我加了s

### ISSUE THREAD

**Issue by MrYZhou** [acmestack/gorm-plus#80]
![image](https://github.com/acmestack/gorm-plus/assets/44339602/31dd7f0c-128c-47f9-b5d6-23f35073dead)

type Config struct {
	Id  string 
	Name string
}

![image](https://github.com/acmestack/gorm-plus/assets/44339602/ccf5a39b-6928-4b93-8540-366c036e5e8a)

**Comment by ywly** [comment]
你好，请问解决了吗？我也遇到了这个问题

**Comment by ywly** [comment]
明白了，gorm的问题，需要配置单数表明：
NamingStrategy: schema.NamingStrategy{
			SingularTable: true, // 使用单数表名
		},
